export const authStyles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f1f5f9",
    padding: 20,
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
  },
  card: {
    background: "#f8fafc",
    borderRadius: 16,
    padding: "36px 40px",
    boxShadow: "0 4px 24px rgba(0,0,0,.08)",
    width: "100%",
    maxWidth: 400,
  },
  heading: {
    fontSize: 22,
    fontWeight: 700,
    color: "#0f172a",
    margin: "0 0 22px",
    letterSpacing: "-.4px",
  },
  primaryBtn: {
    width: "100%",
    padding: "11px 0",
    marginTop: 4,
    background: "linear-gradient(135deg,#3b5bdb 0%,#4c6ef5 100%)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(59,91,219,.35)",
    transition: "opacity .15s, transform .1s",
    fontFamily: "inherit",
  },
  linkBtn: {
    background: "none",
    border: "none",
    padding: 0,
    color: "#3b5bdb",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  footerText: {
    textAlign: "center",
    marginTop: 16,
    fontSize: 13,
    color: "#64748b",
  },
  errorBanner: {
    background: "#fef2f2",
    border: "1.5px solid #fca5a5",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 13,
    color: "#dc2626",
    fontWeight: 500,
    marginBottom: 16,
  },
  fieldErr: {
    margin: "-10px 0 10px",
    fontSize: 12,
    color: "#ef4444",
  },
};